title: Vox
description: A Go web framework for humans, heavily inspired by Koa.
url: https://aisk.github.io
baseurl: /vox

theme: just-the-docs
plugins:
  - jekyll-redirect-from

permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: default

aux_links:
  GitHub: https://github.com/aisk/vox
  API reference: https://pkg.go.dev/github.com/aisk/vox
aux_links_new_tab: true

gh_edit_link: true
gh_edit_link_text: Edit this page on GitHub
gh_edit_repository: https://github.com/aisk/vox
gh_edit_branch: master
gh_edit_source: docs
gh_edit_view_mode: edit

back_to_top: true
back_to_top_text: Back to top

enable_copy_code_button: true

callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: yellow

footer_content: 'Copyright &copy; 2016-2026 aisk. Distributed under the <a href="https://github.com/aisk/vox/blob/master/LICENSE">MIT license</a>.'

sass:
  quiet_deps: true
  silence_deprecations:
    - import
